apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise-mongo
  template:
    metadata:
      labels:
        app: exercise-mongo
    spec:
      containers:
        - name: exercise-mongo
          image: mongo
