apiVersion : networking.k8s.io/v1
kind : Ingress
metadata :
  name : ingress-service
  annotations :
    kubernetes.io/ingress.class : nginx
    nginx.ingress.kubernetes.io/use-regex : "true"
    nginx.ingress.kubernetes.io/proxy-body-size : "5000m"
spec :
  rules :
    - host : exercises.dev
      http :
        paths :
          - path : /api/auth/?(.*)
            pathType : Prefix
            backend :
              service :
                name : auth-cluster-ip-service
                port :
                  number : 3000
          - path : /api/exercise/?(.*)
            pathType : Prefix
            backend :
              service :
                name : exercise-cluster-ip-service
                port :
                  number : 3000